### ISSUE TITLE
A follow up would be nice

### ISSUE THREAD

**Issue by theviking** [adnanrahic/nodejs-restful-api#2]
I have a few questions on scaling this up to numerous models and routes. How do you keep the code small and not repeating itself. The CRUD sections seem to just be copy-pastes of itself for each route.  Thanks

**Comment by adnanrahic** [comment]
The routes will always be similar to some extent. You are the one who chooses how to structure the complexity of your application. You can use services and providers to isolate business logic into closed off scopes and only call functions in the actual controller CRUD implementation. Take a peek at [this project](https://github.com/adnanrahic/boilerplate-api) I've been working on for the past few months. It'll hopefully give you more insight into answering your question.
Cheers!

**Comment by theviking** [comment]
Wow. Totally lost track of this post. Sorry. But that you for the link. I will study and hopefully gain a bunch of knowledge. Thanks!
